stages:
  import_data:
    cmd: python -m src.data.import_data
    deps:
    - src/config/config.py
    - src/data/check_structure.py
    - src/data/import_data.py
    outs:
    - data/raw_data

  make_dataset:
    cmd: python -m src.data.make_dataset
    deps:
    - src/config/config.py
    - src/data/check_structure.py
    - src/data/make_dataset.py
    - data/raw_data
    outs:
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    - data/processed_data/y_train.csv
    - data/processed_data/y_test.csv

  normalize_data:
    cmd: python -m src.data.normalize_data
    deps:
    - src/config/config.py
    - src/data/normalize_data.py
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    outs:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/X_test_scaled.csv

  grid_search:
    cmd: python -m src.models.searching_params
    deps:
    - src/config/config.py
    - src/models/searching_params.py
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    outs:
    - models/best_params.pkl

  training:
    cmd: python -m src.models.train
    deps:
    - src/config/config.py
    - src/models/train.py
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    outs:
    - models/trained_model.pkl

  evaluation:
    cmd: python -m src.models.eval
    deps:
    - src/config/config.py
    - src/models/eval.py
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/trained_model.pkl
    metrics:
      - metrics/scores.json:
          cache: false
    outs:
    - data/predictions.csv